### ISSUE TITLE
Przygotowanie pliku .proto i wygenerowanie klas dla Javy i C++

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#1]
Struktury które należy wygenerować:
wierzchołków (punkt, numer),
krawędzi (para punktów),
trójkątnych ścian (trzy punkty),
czworościennych brył (cztery punkty),

Przykład użycia protocol buffer - JavaAPI/Smeshalist/src/structDefinitions/

**Comment by kakoniec** [comment]
ja mam pytanie i wniosek
po co komu pole number w vertexach? wnoszę o jego usunięcie albo przynajmniej zmianę na optional, bo jest głupie

**Comment by wdymek** [comment]
przychylam się do wniosku, pole nieużywane raczej, powody jego dodania - nieznane :smiley:

**Comment by ew940709** [comment]
Sam to wymyśliłeś :D Ale jeżeli nie jest potrzebne to vertex jest całkiem do wywalenia
