### ISSUE TITLE
Drzewko struktur - statystyki

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#12]
Należy dodać funkcjonalność gromadzenia statystyk takich jak:
- ogólna liczba oraz ilość aktualnie wyświetlanych struktur każdego rodzaju
- prostopadłościan ograniczający - czyli współrzędne prostopadłościanu ograniczającego wszystkie struktury na scenie
  Zapewne wyznaczanie statystyk trzeba będzie dodać w metodzie add.

**Comment by CharlieBr** [comment]
Teraz zarowno statystyki dotyczace ogolnej liczby elemntow, jak i tych widocznych aktualizowane sa podczas dodawania elementow do struktur. Jesli uzytkownik doda powiedzmy 50 elementow i potem zmieni filtrowanie, nalezy wywolac metode count_visible_elements() uaktualniajaca liczniki widocznych elementow, po to aby mogly byc dodawane kolejne elementy i dane dotyczace statystyk byly prawidlowe.

**Comment by wdymek** [comment]
@CharlieBr po szybkim przejrzeniu kodu mam 3 uwagi (jeśli były to zabiegi w pełni zamierzone i sensowne albo ja czegoś nie zauważyłem to sory ;) ):
- (taka techniczna pierdołka) w Data.h deklarujesz mapy jako statyczne, natomiast metody które na nich operują statyczne nie są
- wartościami w mapach są inty a zwracasz longi (no chyba że założyłaś że w mapie pojemność inta jest wystarczy, natomiast boisz się overflowa przy sumowaniu, to wtedy ok)
- pole quality powinno być raczej double, int mocno ogranicza w tej sytuacji
