### ISSUE TITLE
Smeshalist Manager - zakładka Filtry

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#16]
Filtry - złożony widok, który umożliwia użytkownikowi tworzeniem warunków na:
- Grupy
- Współrzędne
- Jakość
- Rodzaj

Po naciśnięciu przycisku Zastosuj tworzony jest obiekt zawierający wszystkie filtry (obojętnie w której pod-zakładce jesteśmy). Sama struktura obiektu nie powinna być złożona - Grupy i Rodzaje to same flagi Boolean, a Współrzędne i Jakość to zbiory współczynników (i operatorów). Poniżej opis pod-zakładek, począwszy od widoków najprostrzych.

**Rodzaj**
Stała lista dostępnych struktur. Po zmianie stanu checkboxa również wysyłamy pełen zestaw filtrów (no chyba że również tutaj i poniżej wprowadzamy przycisk Zastosuj - użytkownicy lubią nadużywać tego typu przycisków).

**Grupy**
Listę dostępnych grup SM otrzymuje od Cora, również poprzez UDP - po każdym dodaniu przez użytkownika struktur moduł drzewka sprawdza czy nie pojawiła się nowa grupa, jeśli tak to info idzie do Cora, które przesyła je do SM. Za każdym razem dostarcza pełnej listy dostępnych grup.

**Jakość**
Umożliwiamy użytkownikowi tworzenie przedziałów, w których powinien się znaleźć współczynnik jakości. Warunki są łączone spójnikiem OR - nie ma raczej sensu robić jakiś przecięć przedziałów, to samo można uzyskać odpowiednio modyfikując przedziały - jak użytkownik nie ogarnia to jego strata.
Dodawanie warunku odbywa się poprzez wypełnienie przynajmniej jednego z pół V1/V2 i wybraniu operatorów (<, <=, =). Jeżeli nie wypełni jednego z pól V1/V2 uznajemy że przedział ma być jednostronnie nieograniczony. Zatwierdz przyciskiem DODAJ - powoduje to również pojawienie się nowego panelu z całym nowo dodanym warunkiem. Usuwanie - wiadomo.

**Wpółrzędne**
Chyba najważniejszy widok. Umożliwia ograniczanie płaszczyznami. Logika działania analogicznie do zakładki Jakość. Wprowadzamy conajmniej jeden ze współczynników {x, y, z} oraz wyraz wolny D. Wybieramy operator (<, <=, >=, >). Reszta tak samo jak Jakość.

To tylko skrótowy opis, pytania i propozycje mile widziane ;)
No i tak samo jak w przypadku ogólnego opisu - to tylko mock - w praktyce pewnie będzie wyglądał trochę inaczej (a już na pewno dużo bardziej user friendly)

**Comment by wdymek** [comment]
Do zrobienia w najbliższym czasie:
1) obsługa przycisków Delete
2) dodanie walidacji - obecnie można w textFieldy wpisywać wszystko (docelowo tylko double)
3) opcjonalnie - dodanie walidacji aby nie można było dodawać bezsensownych filtrów postaci 10 < quality < 5
4) w Coordinates zamiast pierwszego textFielda dałbym jednak comboBox z trzema wartościami, za pozostałymi polami jakieś labelki żeby było jasne której zmiennej się dany współczynnik tyczy (no i oczywiście bajer taki że jak użytkownik przeklikuje się na comboBoxie to labelki też się powinny zmieniać)

**Comment by wdymek** [comment]
@kakoniec zgodnie z rozmową, wycofuję się z roszczenia numer 4 ;)
Jedna rzecz do dorobienia - w zakładce Coordinates w przypadku liczb dodatnich powinien pojawić się znak "+" (dotyczy współczynników przy y i z)

**Comment by wdymek** [comment]
Tutaj będzie jeszcze do dodania obsługa filtrów które są przedziałami jednostronnie otwartymi

**Comment by kakoniec** [comment]
Można dodać warunek z jedną nierównością

**Comment by kakoniec** [comment]
Tutaj jest trochę dziko to zrobione, teraz widzę. Bo operator w wiadomości do Core to enum (EQUAL, LESS, LESS_OR_EQUAL). Tylko teraz w przypadku leftOperator to chociaż jest on '<=' (czy tam '<') to po swojej stronie Core musi go traktować jako '>=' (względnie '>').
