### ISSUE TITLE
Konfiguracja użytkownika

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#19]
Zgodnie z sugestiami p. Jurczyka, należałoby dodać jakiś mechanizm pozwalający użytkownikowi modyfikowanie pewnych zmiennych w aplikacji.
Wstępnie, moglibyśmy dodać możliwość zmiany mapy kolorów przypisywanych grupom (możemy się również zastanowić czy nie pozwolić użytkownikowi np. na zmiany portów). Wydaje mi się że w przypadku tak prostych konfiguracji nie musimy brnąć w żadne xmle (chyba że znacie jakieś gotowe parsery etc) – wystarczyłby format zapisu klucz:wartość.
Co o tym sądzicie?

**Comment by kakoniec** [comment]
Dobry pomysł.
