### ISSUE TITLE
Drzewko struktur - mapa kolorów

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#20]
Struktury należące do różnych grup powinny mieć różne kolory.
Implementacyjnie mogłoby to wyglądać tak, że drzewko przechowuje sobie mapę grupa→kolor. Początkowo jest ona pusta. W trakcie dodawania nowych struktur mamy ifa, który sprawdza czy dana grupa już istnieje – w przypadku dodawania nowej, do mapy kolorów powinna powędrować nowa para wartości. Sam algorytm doboru kolorów przedyskutujemy później – chwilowo może to być zwykły random, jednak docelowo dobór kolorów powinien być deterministyczny, tak aby przy każdorazowym odpaleniu aplikacji kolor grupy był taki sam.
W grę również wchodzi konfiguracja użytkownika – temat realizowany w osobnym tasku.

**Comment by wdymek** [comment]
Propozycja deterministycznego algorytmu wyznaczania kolorów:
R = 255 \* |sin(groupID)|
G = 255 \* |cos(0,5 \* groupID)|
B = 255 \* |sin(0,1 \* groupID)|
Zapewne współczynniki trzeba będzie dobrać już eksperymentalnie, jednak uważam że taki sposób zapewni nam łatwy sposób rozlosowania kolorów dla grup.

Co do konfiguracji użytkownika - myślę że powinno to wyglądać tak, że moduł odpowiedzialny za jej przeczytania wystawia metodę getColorForGroup(int) - jeżeli zwróci coś sensownego to oznacza że użytkownik zdefiniował sobie korol dla tej grupy, drzewko dopisuje go sobie do swojej mapy i stosuje. Jeśli moduł zwróci śmieci (np (R,G,B)=(-1,-1,-1)) to oznacza że należy zastosować defaultowy algorytm do stworzenia sobie kolorku.

**Comment by wdymek** [comment]
@CharlieBr po dodaniu rysowania boundingBox'a i filtrów zauważyłem że niektóre struktury nie mają explicite wywoływanej metody glColor przez co na tą chwilę mogą rysować się z błędnym kolorem.
Problem z pewnością zostanie rozwiązany w tym zgłoszeniu, dlatego nie zgłaszam osobnego taska, zwracam tylko uwagę żeby o tym nie zapomnieć ;)

**Comment by CharlieBr** [comment]
Ponieważ funkcja `glColor3f()` wymaga wartości z przedziału <0.0, 1.0> konieczna była niewielka zmiana algorytmu generowania koloru, teraz:
R = |sin(groupID)|
G = |cos(0,5 \* groupID)|
B = |sin(0,1 \* groupID)|
