### ISSUE TITLE
Rozwój API javowego – realizacja #9 – wiadomości sterujące

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#24]
Należy stworzyć nowy typ wiadomości. Powinna ona zawierać pole enum z wartościami DATA_STRUCTURES, BREAKPOINT, RENDER (te będą szły od strony klienta), CONTINUE oraz ABORT (od strony serwera, oczekiwane po wysłaniu breakpointa).
Dodatkowo, powinna powstać jedna klasa opakowująca wszystkie możliwe zbiory struktur + pole, które informuje o tym, czy dana paczka jest ostatnia (czy serwer ma jeszcze na jakieś oczekiwać).
Schematy komunikacji:
1) RENDER – klient wysyła żądanie odświeżenia widoku i tyle
2) BREAKPOINT – klient wysyła wiadomość i oczekuje odpowiedzi CONTINUE/ABORT(w tym przypadku powinniśmy ubijać całą aplikację po stronie klienta)
3) DATA_STRUCTURES – zapoczątkowuje wysyłanie paczek z danymi, transfer kończymy zmianą flagi w paczce na przeciwną.

**Comment by ew940709** [comment]
Dodane do JAVA API
