### ISSUE TITLE
SmeshalistManager – warstwa komunikacji – plik .proto

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#25]
Należy przygotować plik .proto z wiadomościami, które będą wymieniane pomiędzy SM a Corem.
1) statystyki – (Core → SM) wiadomość sterująca zakładką Statystyki (któż by się domyślił xD), zapewne będzie zawierać dokładnie te same info które jest prezentowane w zakładce
2) breakpoint – (Core → SM) wiadomość która powinna aktywować przyciski na panelu opcji.
//można te wiadomości połączyć w jedną, z dodatkowym polem ENUM mówiącym o typie wiadomości, tak aby uniknąć problemów z rozpoznaniem co to za wiadomość (musielibyśmy próbować castować wiadomość, łapać wyjątki jeśli się okaże że to inny typ wiadomości etc) – rozwiązaniem na około są wiadomości sterujące
3) komunikację na linii SM→Core w całości oparłbym na jednym typie wiadomości. Zawierałaby ona info z obu paneli (opcje oraz filtry). Co do filtrów – przydałoby się pole które mówiłoby czy filtry były modyfikowane – jeśli nie to wgl nie przesyłamy tych filtrów, jeśli tak – wiadomo, uzupełniamy skrupulatnie wszystkie pola. Tutaj zapewne przyda się jakaś grubsza dekompozycja.

To tylko moja propozycja, @kakoniec gdyby się okazało że potrzeba czegoś więcej albo że to nie ma sensu - pisz czym prędzej ;)

**Comment by wdymek** [comment]
do statystyk należałoby jeszcze dodać informacje o dostępnych grupach (do sterowania panelam Filters->Groups)

**Comment by kakoniec** [comment]
ManagerToCoreMessage ma obowiązkowe pole messageType oraz pola opcjonalne (opcje i każdy z filtróe). Jeżeli były jakieś zmiany w filtrze to zostaje on dodany do wiadomości, wpp nie. Po drugiej stronie należy spraqwdzać po prostu metodą udostępnianą przez protobuf message.hasXFilter() czy dany filtr został przesłany.
