### ISSUE TITLE
Drzewko struktur – wyświetlanie labelki

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#26]
W pierwszej kolejności należy wykminić w jaki sposób tworzone są czcionki w OpenGL i jak z nich korzystać (WARNING jeśli okaże się że jest to jakoś zależne od systemu operacyjnego dobrze by było oddzielić to jak tylko możliwe od tego co już mamy żeby pod Windowsem nie trzeba było pisać/zmieniać klas drzewka struktur).
W drugiej kolejności trzeba poeksperymentować z wyświetlaniem takiej labelki – powinna ona jakoś przylegać do elementu do którego się odnosi + użytkownik zawsze powinien wiedzieć ją od przodu, niezależnie od obrotu kamery (mam nadzieję że wystarczy tutaj zabawa z glPushMatrix/glPopMatrix)
Dodatkowo, drzewko powinno wystawić jakąś metodę, dzięki której z zewnątrz można by sterować widocznością labelki.

**Comment by wdymek** [comment]
https://www.opengl.org/archives/resources/features/fontsurvey/#glut
powinno załatwić sprawę, trzeba jeszcze to porządnie przetestować czy zadziała ;)

**Comment by wdymek** [comment]
Przenoszę na Release v1.1 i podbijam temat ;)

**Comment by wdymek** [comment]
@CharlieBr udało mi się znaleźć coś co może nas ratować - funkcja gluProject - zwraca współrzędne punktu po zrzutowaniu na ekran - wystarczy że będziemy potrafili pisać coś po samej płaszczyźnie ekranu, wtedy współrzędne sobie wyliczymy i gitara :wink:

**Comment by wdymek** [comment]
https://www.youtube.com/watch?v=BgIsTZiyvvU
+ link z opisu powinny pomóc

**Comment by CharlieBr** [comment]
![labels](https://cloud.githubusercontent.com/assets/15144528/21204379/7248a35e-c257-11e6-9fa6-ad335e6743a5.png)

☝️ wstępnie wygląda to tak. Czekam na ewentualne sugestie odnośnie wielkości tekstu (obecnie 10, do wyboru 12 i 18 z tego co się orientuję), koloru (taki jak kolor elementu - przynajmniej w teorii, nie wiem czy to przez oświetlenie się czasami różnią czy jakieś inne parametry), umiejscowienia etykietki (punkty - nad, krawędzie - po prawej stronie punktu środkowego, ściany i bloki - nad najwyższym punktem).

Co do ostatniego, u mnie bardzo słabo widać punkty ogólnie. Przy włączonych etykietach tekst się nakłada i ich nie widać całkowicie. Przy większej odległości jest z kolei problem przy przybliżaniu - etykieta jest zbyt oddalona od punktu i przy kilku elementach może być ciężko się połapać co jest do czego.
