### ISSUE TITLE
SmeshalistManager – warstwa komunikacji – socket

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#27]
Należy przygotować klasę/klasy które będą się w stanie komunikować z Core'em.
Załóżmy, że serwer wystawia socket na porcie 8393.
SmeshalistManager powinien być w stanie jednocześnie odbierać i nadawać wiadomości (filtry i statystyki zmieniają się niezależnie więc i komunikacja musi być asynchroniczna). Zapewne w komunikacji potrzebne będą dwa wątki. Według stackoverflow da się to bez problemu zrobić (symultaniczne korzystanie dwóch wątków z jednego socketa).
Jeden wątek będzie odpowiedzialny za otrzymywanie statystyk.
Drugi wątek będzie wysyłał dane z SM.

**Comment by kakoniec** [comment]
SmeshalistManager gotowy do komunikacji z Core (w teorii). Czekam na implementację od strony Core żeby sprawdzić działanie :wink:
