### ISSUE TITLE
Smeshalist PythonAPI – implementacja

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#28]
Należy przepisać API klienckie do języka Python. W razie potrzeby – wszystkie potrzebne issues są olabelowane poprzez JavaAPI.

**Comment by kakoniec** [comment]
W pythonie istnieje możliwość tworzenia klas abstrakcyjnych. Można się zastanowić czy ten właśnie mechanizm nie byłby użyteczny do stworzenia klas struktur geometrycznych.

**Comment by ew940709** [comment]
Zaimplementowane, branche zostały zmergowane
