### ISSUE TITLE
Smeshalist CppAPI/Linux – implementacja

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#30]
Należy przepisać API klienckie do języka C++ (w wersji na Linuxa). W razie potrzeby – wszystkie potrzebne issues są olabelowane poprzez JavaAPI. Task powiązany z implementacją na wersję Windowsową – polecam zawarcie jak największej części logiki w klasie abstrakcyjnej, natomiast specyficzne wywołania metod w dedykowanej implementacji (podobnie jak w COMMUNICATION_MODULE). Pliki proto są już wygenerowane na potrzeby Core.

**Comment by kakoniec** [comment]
Smeshalist w zakresie GetInstance(), AddGeometry(), FlushBuffer(), Render() i Breakpoint() zaimplementowane w ramach CharlieBr@9cad034efe946b902ecff386a0801c05f459f9ca and CharlieBr@f4a72850a219d5bf974374e0b423258dbe055ccb
