### ISSUE TITLE
SmeshalistManager - wiadomość Hello

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#36]
SmeshalistManager działa na porcie efemerycznym, innym z każdym uruchomieniem, przez co Core nie może mieć zaszytych w kodzie namiarów.
Problem pojawia się gdy to Core musi jako pierwszy wysłać wiadomość do SM - nie wiadomo na który port. Na tą chwilę wystarczy kliknąć na początku na cokolwiek w SM, wtedy Core zapisuje sobie namiary i wszystko śmiga ;)
Sugeruję dodanie jeszcze jednego typu wiadomości (chociażby wspomnianego Hello), które byłoby wysyłane do Core natychmiast po utworzeniu socketu.

**Comment by kakoniec** [comment]
Albo można bindować ten socket przy jego tworzeniu to tego portu, na który zawsze wysyłam wiadomości (8393)??

**Comment by wdymek** [comment]
Teoretycznie tak, ale trzeba by sprawdzić jak się to zachowa - SM posiada dwa wątki - wysyłający i nasłuchujący - nie wiem czy nasłuchujący nie będzie chciał również tej wiadomości odebrać. Jeśli tak, musielibyśmy sprawdzać skąd pochodzi ta wiadomość, czy nie odbieramy od samego siebie, takie same sprawdzenie musiało by być po stronie Core, co jak dla mnie przemawia za opcją "z przywitaniem" ;)
Takie myki z bindowaniem kilku aplikacji do jednego portu stosuje się przy multicascie, więc oczywiście da się coś takiego zrobić.
