### ISSUE TITLE
SmeshalistManager - przepisywanie grup jako typów

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#39]
Przesyłam statystyki do SM. Grupy pojawiają się w zakładce Types zamiast Groups.
Osobiście, nie podoba mi się ten kawałeczek w FiltersTab.java:
public void setGroupsInfo(GroupsInfo groupsInfo){
    typesTab.setStructures(groupsInfo.getAllGroupsList());
}

**Comment by kakoniec** [comment]
Lista typów raczej powinna być zahardkodowana..? W trakcie działania nie dodamy nowego typu, a gdyby był jakiś nowy potrzebny no to i tak trzeba wszędzie dodawać
