### ISSUE TITLE
SmeshalistManager - poprawki do GUI - task zbiorczy

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#41]
1) przydałoby się jakoś ograniczyć dokładność wyświetlanego BoundingBoxa, mamy za dużo cyfr przez co staje się to nieczytelne
2) po odebraniu danych nie idzie automatycznie repaint, przez co dane albo się nie odświeżają albo dzieją się cuda jak te na załączniku //po stronie core obsłużę jeszcze translację żeby labelki pozostawały takie same
3) usunąć przykładowe dane (albo np bounding box ustawić na [0,0]x[0,0]x[0,0], defaultowo zostawić tylko grupę 0 etc)

**Comment by wdymek** [comment]
4) uzgodnienie defaultowych wartości niektórych opcji - na tą chwilę mamy między nimi rozjazd
Przykład: Core zakłada że dynamiczny rendering jest włączony, natomiast na SM check box jest wyłączony
Przykład 2: czułość myszki również ma niezgodną wartość na linii Core <-> SM
Pomysł jest dosyć prosty - po wiadomości Hello, SM wysyłałby wszystkie dane z panelu opcje (do weryfikacji czy tylko z tego), dzięki czemu ustalanie jakiś defaultowych wartości leżałoby tylko po stronie SM - nie musielibyśmy zmieniać tego zaszywać w obu miejscach.

**Comment by kakoniec** [comment]
Można od razu w Hello przesłać uzupełnione pole optionsInfo?

**Comment by wdymek** [comment]
@kakoniec why not ;)

**Comment by kakoniec** [comment]
5) w GroupsTab grupy są nadpisywane z każdym nadejściem statystyk i tracona jest informacja o selekcji
6) domyślnie powinny być wybrane wszystkie checkboxy w TypesTab i GroupsTab

**Comment by kakoniec** [comment]
7) po CLEAN powinny się usuwać checkboxy gup z zakładki Groups

**Comment by wdymek** [comment]
8) dodanie tytułu okienka, pleeeaaase :smiley: 
9) pod rozkminę - jak chcemy rozegrać kwestię mapowania kolor<=>grupa w SM; moje dwie propozycje:
- hardcore - użytkownik może sobie skonfigurować kolor w SM
- lajt static - Core określa sobie kolor i przesyła w GroupsInfo

**Comment by wdymek** [comment]
Pozwolę sobie tutaj jeszcze zadać pytanie, bo myślę nad tym cleanem.
Może warto by zmienić funkcjonalność tak że clean dla drzewka current czyściłby go, natomiast dla prev usuwałby takiego snapa z listy. Na tą chwilę po zrobieniu snapa pozostaje dostępny po wsze czasy + po kliknięciu clean nic się nie dzieje co jest nieintuicyjne.

**Comment by wdymek** [comment]
Większych poprawek raczej już nie będzie.
Jest jeszcze jedna rzecz + import/eksport, ale to już raczej w osobnych zgłoszeniach także @kakoniec możesz zamykać ;)
