### ISSUE TITLE
Drzewko struktur - założenia podczas liczenia statystyk

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#42]
@CharlieBr nad ifem(line:102 Data.cpp) dodałaś komentarz "assumed that all elements have the same to_draw flag". W module komunikacji dane są już i tak cachowane w postaci dokładnie takiej w jakiej trafią do drzewka i ciężko byłoby tam to jeszcze porozdzielać. Czy dałabyś radę dołożyć w tej metodzie zliczanie widocznych elementów w wektorze elements i na tej podstawie updatowała statystyki?

Dodatkowo, nie zostało tutaj uwzględnione to że jeżeli element sam w sobie jest drawable ale trafi do grupy/typu który rysowany nie jest to nie powinien on być wliczany do statystyk.
Należałoby tutaj jeszcze dodać dwa warunki - czy grupa jest rysowana i czy typ jest rysowany, dopiero wtedy zliczać ilość rysowanych elementów w wektorze

**Comment by CharlieBr** [comment]
@dymekw Czy jeśli jako element dodawana jest linia z `to_draw = true` i trafi oczywiście do grupy, która ma być rysowana, to te 2 punkty, z których się składa także zliczać jako widoczne?

**Comment by wdymek** [comment]
nie, nie rozbijamy tego tak że edge to edge+2 punkty tylko traktujemy to jako jeden obiekt
