### ISSUE TITLE
Zmiana algorytmu działania metody flushBuffer

### ISSUE THREAD

**Issue by kakoniec** [CharlieBr/Smeshalist#43]
Zmiany do wprowadzenia:

Mamy parametr określający max. ilość elementów wysyłanych w jednej paczce niezależnie od ich typu.

Początek pozostaje taki sam: 
- wywołanie metod addGeometry()
- wywołanie flushBuffer()
- Smeshalist wysyła MessageType.DATA
- czeka na odpowiedź ACK
- po otrzymaniu ACK iterujemy po liście struktur do wysłania i pakujemy po określoną parametrem ilość (wartość parametru pozostaje do wyznaczenia)
- wysyłamy najpierw Header z informacją ile bajtów danych przyjdzie następną wiadomością i czy następna wiadomość jest już ostatnia, Header ma stały rozmiar 64B (do ustalenia)
- (w tym miejscu może być konieczne wprowadzenie kontroli przesyłanych danych, bo nie wiem jak to zadziała wszystko na UDP z kolejnością i ew. gubieniem paczek)
- wysyłamy właściwe dane struktur

**Comment by wdymek** [comment]
Podmieniłem protokół po swojej stronie.
Wywaliło mi coś takiego:
Exception in thread "main" java.lang.IllegalArgumentException: illegal length or offset
        at java.net.DatagramPacket.setData(DatagramPacket.java:267)
        at java.net.DatagramPacket.<init>(DatagramPacket.java:121)
        at java.net.DatagramPacket.<init>(DatagramPacket.java:161)
        **at tool.Smeshalist.flushBuffer(Smeshalist.java:210)**
        at test.App.main(App.java:67)

Chyba zaszycie tych 64B nie zadziałało jak powinno ;)
