### ISSUE TITLE
Usunięcie vertex z proto

### ISSUE THREAD

**Issue by ew940709** [CharlieBr/Smeshalist#46]
Należy usunąć ten niezidentyfikowany twór jakim jest vertex, gdyż bez pola number nie ma w ogóle sensu trzymać, bo jest to zwykły point3D

**Comment by kakoniec** [comment]
ja bym usuwała Point2d i Point3d jak już coś

**Comment by ew940709** [comment]
wszystkie inne obiekty korzystają z tego, nie rozumiem czemu chcesz to usunąc i zmieniać teraz wszędzie na vertexy

**Comment by kakoniec** [comment]
najładniej by było jakby point3d nie miał propsów, vertex miałby pointa i by było, nie upieram się, ale podoba mi się vertex bardziej niż point3d :D

**Comment by ew940709** [comment]
Jak dla mnie to tylko nazwa. Usunięcie point3d spowoduje że trzeba to w kilkunastu miejscach zmieniać.

**Comment by kakoniec** [comment]
no to nie usuwać właśnie, tylko wywalić z niego propsy, takie spójne mi się to bardziej wydaje jak wszystkie struktury zawierałyby Point3d, tylko uniemożliwić jak coś dodanie bezpośrednio za pomocą metody addGeometry(Point3D)

**Comment by wdymek** [comment]
mi się osobiście bardziej podobają więcej mówiące nazwy Point3D i Point2D
z drugiej strony racja co do tych propsów - nie potrzebnie mieć pole propertisów z którego nie korzystamy - tak jak np w bardziej złożonych strukturach dla których liczy się pole prop bezpośrednio w nim a nie w pointach.

**Comment by wdymek** [comment]
w pierwszej kolejności usunąłbym Point2D - nie wnosi większej wygody, a już odpada nam jeden typ

**Comment by ew940709** [comment]
Przemyślałam to i może lepiej wywalić propy z punktu3D i mieć vertex ktory posiada punkt i propy, ale nie zmieniać wtedy bloków, krawędzi i ścian i wtedy nie bedzie sie dało ustawić properties na poszczególnych wierzchołkach budujących te struktury, tylko na całej gotowej strukturze. Pytanie ile zmian trzeba będzie wprowadzić w CommunicationModule @dymekw ?

**Comment by wdymek** [comment]
Po mojej stronie dosłownie parę linijek, więc nie widzę problemów
@CharlieBr czy widzisz jakieś większe problemy z drzewkiem struktur?

**Comment by CharlieBr** [comment]
Hm,  ja w strukturze drzewka mam tylko `Point3D` jako "opakowanie" na współrzędne (w tym punkt 2D - współrzędna z-owa jest po prostu równa 0). On nie ma żadnych innych atrybutów. `Vertex` natomiast reprezentuje element do wyświetlenia - jego klasa dziedziczy po `Element` i tu już występują wszystkie atrybuty. 

@dymekw Jeśli więc ma być tak jak pisze @ew940709, żeby `Vertex` miał `Point3D`, to w strukturach tak własnie jest i żadne zmiany nie będą konieczne chyba :smiley:

Inna sprawa jesli chcemy je scalić, żeby `Vertex` nie miał atrybutu `Point3D`, tylko współrzędne `x`, `y`, `z`. Wydaje mi się, że to nie powinno stanowić problemu, po prostu będę musiała zmienić obsługę najniższego poziomu drzewka. Może być z tym trochę zabawy ale nie jakoś dużo mam nadzieję. 

Musimy tylko się zdecydować na nazwę. Osobiście jestem za **Vertex**, bo w sumie wydaje mi się, że nie potrzebujemy nawet rozróżnienia na Point2D i Point3D. Jesli jednak uważacie, że to jest za dużo zmian to okej (choć ja tam akurat jestem za zmianami bardzo :smiling_imp:, ale ponieważ nie mój kawałek kodu to nie nalegam, chyba, że ktoś mi pokaże gdzie to mogę zmieniać)

**Comment by kakoniec** [comment]
No i to mi się podoba: Baj Baj z Point2D, który nie ma sensu. Point3D traci properties i nie jest utożsamiany z Vertexem ale czymś co opisuje wszystkie rodzaje struktur. Vertex zostaje i ma swoje properties, ale wywalamy z niego dziwne pole number. Czy tak można to podsumować? ;)

**Comment by wdymek** [comment]
@kakoniec szkoda że na gicie nie ma lajków :smile:

**Comment by wdymek** [comment]
@CharlieBr dzięki xD

**Comment by wdymek** [comment]
Poprawka będzie zrealizowana w v1.1
