### ISSUE TITLE
Konfiguracja użytkownika - kontynuacja #19

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#50]
W związku z ostatnimi ustaleniami oraz puntem 9.2 z #41 przydałoby się zrealizować umożliwienie użytkownikowi modyfikacje pewnych parametrów w apce.
Parametry które mi się nasuwają:
- kolor tła (theme=LIGHT|DARK)
- kolor osi (można też dodać możliwość częściowej przezroczystości)
- kolor płaszczyzn filtrów na współrzędne (tak samo jak wyżej)
- kolory grup - zakładam że idziemy właśnie w statyczne ich definiowanie (odrzucamy pomysł z ustawianiem kolorków poprzez SM)
- ścieżka do SM - wywalamy to z argumentów uruchomieniowych (przy okazji należy dodać żeby w przypadku braku (błędnej) ścieżki do SM były sprawdzane jakieś domyślne lokalizacje, np folder z CoreModule (tym uruchomieniowym) oraz w folderze CoreModule/SmeshalistManager)

Czekam na opinie

**Comment by kakoniec** [comment]
Moim zdaniem ustawianie kolorów w SM to już za dużo, użytkownik to programista, prosty xml to dla niego nie problem, a i pewnie zmieniać te kolory i tak mu się zdarzy raz czy dwa, a nie za każdym użyciem. Jestem za tym, żeby przekazywać do SM z core kolor grupy, mogłabym wyświetlić go obok checkboxa.

W ogóle z tym uruchamianiem to nie powinno być tak, że wszystko się samo włączy? I CoreModule i SM przy wywołaniu odpowiedniego GetInstance jakoś? ;D

**Comment by wdymek** [comment]
Z pierwszym zgodzę się jak najbardziej ;)

Co do drugiego powiem tak, jak używałem tego w praktyce to raczej automatyczne odpalanie byłoby dla mnie większym problemem niż udogodnieniem, gdyż:
1) pisanie tych wszystkich algorytmów sprowadzało się bardziej do "napisz-odpal-sprawdź-_clean_-popraw" i tak w kółko, więc przy każdym odpaleniu algorytmu trzeba by zamykać całego Smeshalista, albo kombinować jak sprawdzać czy nie jest już odpalony
2) sam proces automatycznego odpalania nie jest taki prosty - po uruchomieniu CoreModule (które samo w sobie troszku pewnie będzie trwało), następuje odpalenie JVM i na nim SM a to już jest kwestia sekundy/dwóch. Jeżeli user nie miałby żadnych breakpointów to zapewne algorytm by się skończył zanim SM by się odpalił ;) Rozwiązaniem byłoby przesłanie jako argument do CoreModule numeru portu klienta, Core po otrzymaniu wiadomości Hello z SM odsyłałby jakiś ACK do klienta który oczekiwałby cały czas w metodzie getInstance - przyznacie że się wszystko trochę komplikuje ;)

Jak dla mnie odpalenie sobie raz całego Smeshalista, napisanie algorytmu, odpalenie go, sprawdzenie rezultatu, poprzeklinanie sobie, zrobienie cleana i poprawienie algorytmu jest jak najbardziej spoko, zwłaszcza że mamy już te wszystko continue, abort, clean.

**Comment by kakoniec** [comment]
Ok. Spoko, mówisz z sensem :P

**Comment by CharlieBr** [comment]
Ja także bym odpuściła kolor tła. Kolory i przezroczystość osi już prędzej, ale też niekoniecznie. Dla mnie wystarczyłaby np. opcja pokaż/ukryj osie. (Ale nie wiem co prościej zrobić) Filtry tak, ale bardziej przezroczystość. 

I 2 pytania:

> kolory grup - zakładam że idziemy właśnie w statyczne ich definiowanie

:point_up: Jakieś czytanie z pliku czy coś?

> ścieżka do SM

:point_up: Nie jestem pewna czy do końca rozumiem ideę ściezki dostępu do SM i jego domyślnej lokalizacji oraz czy w ogóle to może tak być, ale: czy nie dałoby się założyć, że skoro użytkownik będzie ściągał całego Smeshalista, to raczej nie będzie nigdzie nic przenosił? A skoro gdzieś tam w planach mamy refactoringi i reorganizacje, to może warto by było stworzyć jakiś folder w stylu `Ej tu masz wszystko co Ci potrzeba do reszty nie musisz zaglądać` ? Użytkownik by sobie tam wchodził, kompilował i uruchamiał z jednego poziomu wszystko co konieczne, reszta by go nie obchodziła. 

To tylko taki luźny pomysł, bo domyślałm się, że to by mogło pociągać za sobą jakieś straszne ilości zmian, no i wszystko mogłoby się poburzyć, więc może nie warto się w to bawić.

**Comment by kakoniec** [comment]
Zgadzam się właśnie co do tego uruchamiania, najlepiej by było żeby użytkownik robić i myśleć w minimalnym stopniu o tym jak to uruchomić i w sumie to właśnie nie wiem jak ścieżka do SM mogłaby się zmienić..? 

Co do koloru tła, to umożliwienie zmiany koloru tła na czarny wyszło od Promotora ;)

**Comment by wdymek** [comment]
Co do kolorków - na tą chwilę jest możliwość zdefiniowania koloru tła poprzez ustawienie flagi DARK (w przypadku braku definicji czy też wpisania czegokolwiek z defaultu będzie ono białe).
Jest też możliwość zdefiniowania koloru grupy; przykład:
`<g1 r="0" g="255" b="0"/>` - oznacza że grupa o ID=1 otrzyma kolor zielony
Cały opis konfiguracji użytkownika wrzucę na githubowe wiki, na tą chwilę można podejrzeć plik _user.config.xml_ zamieszczony w CoreModule oraz w folderze Make/Linux

Możliwość konfiguracji ścieżki do SM została dodana tylko ze względu na to, że na ten moment CoreModule jest odpalany w dwojaki sposób - z poziomu CodeBlocks w czasie dev'u oraz z Make/Linux w przypadku testów. Aktualnie w RotateCamera.cpp jest kawałek kodu, który w przypadku braku argumentu _SM_ sprawdza ścieżkę SmeshalistManager/SmeshalistManager.jar - czyli nie musimy podawać argumentu w przypadku uruchamiania z poziomu CodeBlocksa.
W najbliższym czasie pojawi się pewnie więcej ścieżek pod jakimi będzie szukany SM, także w przypadku zrobienia takiej "paczki użytkownika" odpalenie SM nie będzie wymagało podania żadnych argumentów.

**Comment by CharlieBr** [comment]
> Co do koloru tła, to umożliwienie zmiany koloru tła na czarny wyszło od Promotora ;)

OK. Ale rozumiem, że nie musimy zadbać o zmianę ciemnych kolorów elementów na jasne. W sensie, że użytkownik sam sobie zadba o to, żeby widzieć co tam mu potrzebne.

> Jest też możliwość zdefiniowania koloru grupy; przykład: `<g1 r="0" g="255" b="0"/>`

Wiem, że użytkownik to z zasady programista... ale moglibyśmy dodać też parsowanie kolorów w stylu "blue", "green", itp.? (biorę jak coś!)

> czyli nie musimy podawać argumentu w przypadku uruchamiania z poziomu CodeBlocksa.

A jak korzystam z CLion/VisualStudio/DevC++/SublimeText/Gedit to na ten moment musze się zorientować, w którym miejscu mam SM, żeby podać do niego ścieżkę przy uruchamianiu CoreModule?

> W najbliższym czasie pojawi się pewnie więcej ścieżek pod jakimi będzie szukany SM

To jest rzecz, której nie rozumiem - dlaczego nie możemy założyć, że SM nie znajduje się w jednym i tylko jednym miejscu zawsze? W sensie do czego potrzebne są ścieżli w liczbie mnogiej.

**Comment by wdymek** [comment]
> OK. Ale rozumiem, że nie musimy zadbać o zmianę ciemnych kolorów elementów na jasne. W sensie, że użytkownik sam sobie zadba o to, żeby widzieć co tam mu potrzebne.
> Jeżeli użytkownik sobie zdefiniuje że chce mieć wszystkie grupy czarne na ciemnoszarym tle - jego prawo
> 
> Wiem, że użytkownik to z zasady programista... ale moglibyśmy dodać też parsowanie kolorów w stylu "blue", "green", itp.? (biorę jak coś!)
> To jak dla mnie duży szczególik, można dorabiać ale nie trzeba, ja osobiście wolałbym mieć jednolitą notację a nie część grup zdefiniowanych poprzez enumy a część poprzez RGB, no ale to już jak kto woli (priorytet jak dla mnie niski, lepiej sie chwilowo zająć innymi rzeczami :smile: )
> 
> A jak korzystam z CLion/VisualStudio/DevC++/SublimeText/Gedit to na ten moment musze się zorientować, w którym miejscu mam SM, żeby podać do niego ścieżkę przy uruchamianiu CoreModule?
> Optymistycznie założyłem że plik projektu znajduje się dokładnie w CoreModule - w takim przypadku faktycznie odpala się reguła która definiuje odpowiednią ścieżkę dzięki której bez ingerencji z zewnątzr odpala się SM
> 
> To jest rzecz, której nie rozumiem - dlaczego nie możemy założyć, że SM nie znajduje się w jednym i tylko jednym miejscu zawsze? W sensie do czego potrzebne są ścieżli w liczbie mnogiej.
> Tak jak napisałem w komentarzu wyżej - to tylko na nasze potrzeby pisania tego w IDE oraz testowania. To oczywiste że z punktu widzenia użytkownika lepiej mieć zaszytą jedną ścieżkę + ewentualnie możliwość podania jej z palca jako argument jeżeli z jakiś tajemniczych przyczyn by mu się ona nie podobała

**Comment by CharlieBr** [comment]
> priorytet jak dla mnie niski, lepiej sie chwilowo zająć innymi rzeczami

A to oczywiście, tak tylko piszę, że można ewntualnie w przyszłosci wziąć pod rozwagę. Osobiście jak mogę to zawsze wybieram tryb tekstowy definiowania kolorów, bo jest dla mnie szybciej :smiley:

**Comment by wdymek** [comment]
Wersja podstawowa zaimplementowana, kolejne doróbki i poprawki będą procesowane w osobnych zgłoszeniach
