### ISSUE TITLE
SmeshalistManager - przełączanie drzewek

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#53]
Pojawił się pomysł aby przełączanie się pomiędzy drzewkami było sterowane z poziomu SM, a nie za pomocą klawiatury. Rozwiązałoby to problem nieintuicyjnego clean'a (który działa tylko na *Active*).
Ogólnie, polegałoby to na dodaniu np dwóch przycisków ze strzałkami (bądź ComboBox'a), dzięki którym moglibyśmy się przełączać pomiędzy drzewkami + wyszarzanie przycisku Clean jeśli nie wyświetlamy drzewka *Active*.
Pod względem komunikacyjnym - najbardziej odpowiadałyby mi wiadomości typu "select next"/"select prev" zamiast przesyłania indexów.

Temat zapewne jeszcze pod dyskusję jak to ma wyglądać w szczegółach/jak dla użytkownika będzie najwygodniej.

**Comment by kakoniec** [comment]
OK.
To potrzebujemy w proto komunikacyjmym wiadomości typu NEXT_SNAPSHOT, PREV_SNAPSHOT i poruszamy się pojedynczo (wg mnie to najlepsze rozwiązanie, ComboBox niewygodny w użyciu, a chyba dla użytkownika głównym zastosowaniem snapshotów byłoby porównywanie kolejnych wizualizacji algorytmu?  - @dymekw i @CharlieBr poprawcie mnie jeśli się mylę :wink: ). Więc dodanie dwóch przycisków ze strzałką w lewo i w prawo to nie problem. Rozumiem, że dodajemy je do zakładki Options i tam gdzieś upychamy koło Cleana i Snapshota. Wydaje mi się, że wtedy mogłoby być przydatne wyświetlanie również w SM który Snapshot jest pokazywany w głównym oknie.
O czym jeszcze nie pomyślałam?

**Comment by wdymek** [comment]
Jak dla mnie brzmi dobrze :wink:

**Comment by CharlieBr** [comment]
Dla mnie również :slightly_smiling_face:

**Comment by kakoniec** [comment]
To moje zmiany proponowane w proto:
- dodaję jako nowe typy wiadomości NEXT_SNAPSHOT i PREV_SNAPSHOT
- dodanie required string treeName do StatisticsInfo (czy to może być w tym miejscu dodane?)

**Comment by wdymek** [comment]
Zastanawiam się tylko czy nie lepiej nie zrobić NEXT_TREE oraz PREV_TREE - chyba że traktujemy _Active_ jako taki 0 snapshot - to tylko czepianie się o nazewnictwo :wink: 

Co do treeName - w zasadzie będzie musiało, innego wyjścia nie widzę

**Comment by kakoniec** [comment]
Spoko, TREE ma więcej sensu.

W takim razie implementuję jak powyżej.
Danke :)
