### ISSUE TITLE
CoreModule - poprawki/uwagi - task zbiorczy

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#54]
1) dodać oświetlenie (directional light)
2) poprawa poruszania się za pomocą myszki
3) dodać do UserConfigManagera możliwość zmiany koloru osi, płaszczyzn cięcia oraz portu
4) usunąć filtry na grupy w czasie wykonywania operacji clean

**Comment by wdymek** [comment]
5) Przy braku user.config.xml leci segmentation fault - zgłoszone przez najlepszą testerkę ever @ew940709

**Comment by wdymek** [comment]
6) Elementy drzewa powinny być z defaultu niewidoczne, dopiero po zastosowaniu filtrów mogą stać się widoczne

**Comment by wdymek** [comment]
@kakoniec - prośba o pomoc z rozwiązaniem punktu 4
Na tą chwilę SM usuwa całą informację o wyklikanych przez użytkownika filtrach na grupy w momencie kliknięcia opcji Clean. Takie zachowanie jest spoko, ale generuje pewien problem w momencie gdy użytkownik stworzył sobie snapshoty. Przykładowe zachowanie na tą chwilę:
1) user dodaje elementy do grupy 0
2) robi snapshot
3) dodaje elementy do grupy 1
4) ukrywa sobie elementy z grupy 0
5) wykonuje clean
6) przełącza się na _Prev 1_ - w tym momencie w SM pojawia się info o grupie 0 wraz z zaznaczonym CheckBoxem, natomiast Core ciągle ma informacje o tym że użytkownik nie chce widzieć tej grupy i jej nie wyświetla - BUG

Jak dla mnie powinno to zadziałać tak, że jak odklikuje sobie grupę 0 to jest ona niewidoczna wszędzie bez względu na to czy robię w międzyczasie cleany, snapshoty, breakpointy etc.
Wydaje mi się że taki efekt uzyskalibyśmy gdyby SM przechowywał nie tylko informacje, które grupy wyświetlić w zakładce (czyli dokładnie te które otrzymuje w statystykach od Core), ale również globalną mapę <groupID, isVisible>.

Podsumowując, po stronie SM działałoby to tak, że w momencie otrzymania statystyk (w tym grup w wyświetlanym drzewku), następowałoby sprawdzenie czy wpis o widoczności grupy nie znajduje się w globalnej liście, jeśli nie to z defaultu grupa ma być oznaczona jako widoczna.
Implementacyjnie mogłoby to wyglądać tak że jest ta globalna mapa oraz lista z aktualnie wyświetlanymi grupami w zakładce - likwiduje to problem jakieś redundancji i odświeżania paru kolekcji na raz.

@kakoniec jeżeli widzisz tu jakieś luki, albo możliwości że to jednak nie zadziała tak jak myślę, albo masz inny pomysł jak to rozwiązać to daj proszę znać :wink:

**Comment by wdymek** [comment]
Do zrobienia pozostało:
1) dodać oświetlenie (directional light)
2) dodać do UserConfigManagera możliwość zmiany koloru osi, płaszczyzn cięcia oraz portu

**Comment by kakoniec** [comment]
Ja mam jeszcze taką wątpliwość/pytanie: jak możemy sobie filtrować po snapshotach to ja przecież nie zapisuję nigdzie filtrów dodanych dla danego snapshota, co więcej nie usuwam ich nawet (!) - usuwane są tylko po przyciśnięciu przycisku "Clean", który jest włączony tylko dla drzewa głównego. Ja tu widzę kopalnię bugów 😢

**Comment by wdymek** [comment]
Wszystkie grubsze sprawy związane z Corem zostały wykonane.
Jeżeli podejmiemy jakieś działanie odnośnie czyszczenia tych filtrów to poprawki pójdą już w osobnym tasku
@kakoniec do przegadania jutro :wink:
