### ISSUE TITLE
SmeshalistManager - znikająca zawartość tabów

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#57]
Po przesłaniu statystyk, w momencie w którym zawartość zakładek powinna się odświeżyć, cała zawartość znika, pojawia się dopiero po kliknięciu.
Wydaje mi się że problem polega na zbyt szybkim wywoływaniu metod repaint:
```
cell11.removeAll();
cell11.repaint();
cell12.removeAll();
cell12.repaint();
...
```
Metody repaint powinny być wywołane na samym końcu funkcji.
Prośba o sprawdzenie czy to zaradzi na ten problem oraz ewentualne przeklikanie się przez metody o poprawki.

**Comment by wdymek** [comment]
@kakoniec przy aktywnej zakładce Filters-Groups w momencie pojawienia się nowej grupy zakładka się nie odświeża, dalej trzeba kliknąć
Spójrz na to jeszcze proszę

**Comment by CharlieBr** [comment]
Nie mam pojęcia co mi się tu naklikało, przepraszam! :cry:
