### ISSUE TITLE
Hard reset + rzucanie wyjątku w przypadku nieodpalonego Core

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#60]
Metoda getInstance powinna móc przyjmować jeszcze jeden parametr typu bool, mówiący o tym, czy uruchomiona już instancja Smeshalista powinna powrócić do ustawień początkowych czy nie. Tutaj pójdzie również info do SM.
Będzie to więc dodatkowa wiadomość, wysyłana do Core na dzień dobry, którą Core przesyła dalej do SM.

Przy okazji można zrealizować drugą kwestię, czyli rzucenie wyjątku z getInstance w przypadku nieodpalonego Core - w takim przypadku nie będzie potwierdzenia otrzymania wspomnianej flagi hard reset.
Jak dla mnie są dwa rozwiązania:
1) ustawnienie timeoutu na sockecie tylko na czas operacji przesłania flagi HR (czyli robimy socket z timeoutem, w razie powodzenia timeout znika) - na 100% nie jestem pewien czy będzie się to dało tak zrobić, ale na szybko znalazłem coś takiego:
http://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#setSoTimeout(int)
https://docs.python.org/3/library/socket.html#socket.socket.settimeout
https://linux.die.net/man/3/setsockopt + późniejsze ogarnięcie tego na windowsie
2) stały timeout - łatwiejszy, ustawiany raz, jedyny problem mamy przy breakpoincie - na szybko można to zrobić tak że łapiemy timeout i go ignorujemy

Pozostaje tutaj problem sytuacji gdy Core zostaje wyłączony w czasie działania algorytmu, ale to już chyba za gruba sprawa.

**Comment by kakoniec** [comment]
Odnośnie hard reset:
* Dodać typ wiadomości HARD_RESET i po prostu przy wywołaniu odpowiedniego GetInstance() z flagą na true wysłać wiadomość o takim typie. W przypadku false - działa jak GetInstance() bez tego parametru
* dodać typ wiadomości np. HELLO, który zawsze jest wysyłany na początku nieważne, której metody się użyje i wtedy jeszcze pole typu boolean z flagą hard_reset w tej wiadomości

Jak to zrealizować?

**Comment by ew940709** [comment]
dodajesz do MessageInfo HARD_RESET i NO_RESET. Przy wywołaniu getInstance z true wysyłasz HARD_RESET do Core i czekasz na ACK, w przypadku false NO_RESET i czekasz na ACK. Potem wszystko tak samo.

**Comment by kakoniec** [comment]
Czy to już koniec?
Możemy iść?
Jesteśmy wolni?
Bo nie ma już nic? Nic? Nic? Nic?
