### ISSUE TITLE
Zakładka filtrów grup - pomniejsze poprawki/bonusy

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#61]
Zgodnie z ostatnimi konsultacjami, mamy do zrealizowania 3 proste rzeczy:
1) dodanie możliwości przekliknięcia się pomiędzy trybami kolorowania (grupy<->jakość) - mniej powiązane ale przydałaby się informacja na zakładce grup o tym  że aktualne kolory nie odpowiadają tym przypisanym do grup.
2) dodanie przycisku *zaznacz wszystko*
3) dodanie przycisku *odznacz wszystko*

I mała prośba o porządne przeklikanie - czy aby na pewno grupy się odświeżają wtedy kiedy mają, przy cleanach, chodzeniu pomiędzy drzewkami etc

**Comment by kakoniec** [comment]
Jak mam zrealizować punkt 1?
Dodać checkbox w zakładce opcji - "Color structures by quality"?
Czy jakaś lista rozwijana? Jeśli tak to gdzie?

**Comment by wdymek** [comment]
Dla mnie intuicyjne byłyby dwie opcje:
1) przycisk ze zmieniającą się treścią, czyli raz "Color structures by quality", a po wciśnięciu "Color structures by groups" i tak cyklicznie. Problemy dwa - logiczniej byłoby gdyby po wciśnięciu od razu szedł komunikat do Core co trochę się kłóci z przyjętym standardem (wybierz i kliknij Apply), no i komunikaty są trochę przydługawe (no chyba że walniemy border/labelkę z częścią wspólną, a na przycisku tylko "quality"/"groups"). Musielibyśmy też dodać labelkę na zakładce filtrowani po grupach, że wskazywane kolory są nieaktualne dla obecnego kolorowania.
2) lista rozwijana - opcja najprostrza

W checkboxa bym nie szedł z racji tego że chackboxy sposuje się raczej do ustawienia flagi na jakieś opcji/właściwości, a nie do wyboru pomiędzy dwoma różnymi możliwościami. No i za bardzo nie mielibyśmy możliwości poinformowania użytkownika czy koloruje po grupach czy jakości.

**Comment by kakoniec** [comment]
To powiedzmy, że lista rozwijana.
Mam ją wrzucić do zakładki Options?

**Comment by wdymek** [comment]
Jeżeli tylko da się ją jeszcze jakoś logicznie upchnąć to jak najbardziej :wink:

**Comment by kakoniec** [comment]
W communication.proto dodałam enum ColoringType z możliwymi wartościami: GROUP_COLORING i QUALITY_COLORING. 
W OptionsInfo dodałam pole required ColoringType coloringType.

➡️ ➡️ sposób kolorowania jest wysyłany po naciśnięciu "Apply" w zakładce opcji.

Pozostaje update modułu komunikacji ;)

//nie każcie mi już upychać więcej w tej zakładce, bo się popłaczę

**Comment by wdymek** [comment]
@kakoniec prośba o weryfikację
niestety chyba jeszcze tam powędruje przycisk do przełączenia się w tryb 2D :(

**Comment by kakoniec** [comment]
@dymekw przycisk czy lista rozwijana?

**Comment by wdymek** [comment]
@kakoniec myślę że jeżeli miałoby się to znaleźć pod listą do sterowania kolorowaniem to fajnie by było żeby to też była lista

**Comment by kakoniec** [comment]
Lista dodana. Proto zaktualizowane.
Całość zrealizowana analogicznie jak wybór kolorowania struktur, tzn. enum VisualisationMode { MODE_3D, MODE_2D}, w OptionsInfo dodatkowe pole required VisualisationMode visualisationMode.

**Comment by kakoniec** [comment]
Można zamknąć issue?
