### ISSUE TITLE
Globalne przechowywanie filtrów

### ISSUE THREAD

**Issue by kakoniec** [CharlieBr/Smeshalist#69]
Odnośnie punktu 4 z #54 

Przechowywać globalnie filtry dla wszystkich snapshotów w SM.

**Comment by kakoniec** [comment]
@dymekw sprawdzisz czy na pewno działa już jak powinno? 
Ja sprawdzałam tak jak opisałeś w #54 i na mój gust działa, ale lepiej się upewnij 😃

**Comment by wdymek** [comment]
mi również wydaje się że jest ok
pozostawiam przyjemność zamknięcia taska 😉
