### ISSUE TITLE
Smeshialist JavaAPI - wydajność metody Flush()

### ISSUE THREAD

**Issue by ew940709** [CharlieBr/Smeshalist#8]
Trzeba rozkminić jak sensownie napisać metodę flush żeby była jak najbardziej wydajna dla siatek o dużej ilości elementów. Problemem może być to, że bufor szybko się przepełni i będzie kiszka. Pomysłem jest jakieś dzielenie tych danych na części i wysyłanie po trochę, ale jeszcze nie wiadomo jak to konkretnie zrealizować. W tym momencie jest to trochę brzydko zrobione. Możecie to podglądnąć w JavaAPI tool.Smeshialist.

**Comment by wdymek** [comment]
Od siebie dodam jeszcze, że po stronie klienckiej musimy uwzględnić wielkość buffora w sockecie serwera. Proponuję żeby wysyłane datagramy były niewiększe niż np 10'000B
Wydaje mi się że należałoby wprowadzić w sumie dwa mechanizmy:
1) wprowadzić np licznik danych - po 1000 operacjach add robilibyśmy automatycznie flusha
2) przy serializacji trzeba jakoś sprawdzać aktualny rozmiar datagramu - to jeszcze do dokładnego zastanowienia się i dyskusji

**Comment by wdymek** [comment]
Temat powiązał nam się z #6 - tam zaproponowałem następujący schemat komunikacji: wysyłamy MessageInfo z flagą DATA_STRUCTURES, a następnie idą paczki z danymi, czyli wiadomość z uzupełnionymi polami Point2DSet, VertexSet etc.

Co do problemu przepełnienia bufforów – ja bym zastosował proste zliczanie ilości wywołań odpowiednich metod add. W momencie przekroczenia przez licznik wartości np. 1000 konkretny buffor byłby opróżniany.

Teoretycznie datagram z danymi może mieć dowolną wielkość (w MessageInfo moglibyśmy zapisać tą informację i przygotować buffor na dane w serwerze), jednak nie ryzykowałbym wysyłania nie wiadomo jak wielgachnych datagramów – po pierwsze musimy alokować tablice bajtów po obu stronach, co może skończyć się kiepsko. Po drugie „Protocol Buffers are not designed to handle large messages” - zalecane jest wielkość < 1MB. Proponuję następujący algorytm (na pozór pokrętny choć mam nadzieję sensowny):
1) w konstruktorze Smeshalist tworzymy sobie paczki danych, każda z 10 elementami każdego rodzaju.
2) sprawdzamy jej rozmiar, dzielimy przez 10, dzięki czemu mamy estymację ile zajmuje pojedynczy element
3) później stosujemy tą wiedzę przy budowie wiadomości (wiadomo jak – sprawdzamy ile mamy elementów pierwszego rodzaju, jeśli mniej niż powiedzmy 0,1MB to dodajemy wszystkie i uzupełniamy innymi danymi, jeśli zajmują więcej, no to dzielimy i przesyłamy po kawałku).

//sprawdzenie rozmiaru wiadomości => getSerializedSize()

**Comment by wdymek** [comment]
@ew940709 mała poprawka będzie ;) linijka MessageInfo feedback = MessageInfo.parseFrom(response.getData()); nie funkcjonuje tak jak powinna. Problemem jest tutaj to, że odbieramy tylko 2 bajty natomiast response.getData() zwraca nam 10 (czyli tyle ile ma buffor), przez co proto wykrzacza się na parsowaniu. Nie znalazłem metody, która by sobie z tym radziła, roboczo zrobiłem sobie następujące obejście:
1) tworzę roboczą tablicę rozmiaru response.getLength();
2) kopiuje bajty z responseBytes (lub z response.getData())
3) do metody parseFrom przekazuję swoją roboczą tablicę
