### ISSUE TITLE
Rozwój API javowego - wiadomości sterujące

### ISSUE THREAD

**Issue by wdymek** [CharlieBr/Smeshalist#9]
Task na realizację propozycji z #6.
Bezpośrednio po stronie klienta należy dodać metodę breakpoint() która będzie się blokować i czekać na odpowieć ze strony toola. Najlepiej niech zwraca ona integera - będziemy w ten sposób przesyłać info o tym czy użytkownik chce kontynuować obliczenia (zapewne później pojawią się przyciski na toolu - "Kontynuuj" oraz "Przerwij" - w zależności od tego co kliknie to metoda breakpoint zwróci powiedzmy 0/1 które będzie musiałobyć obsłużone jakoś z kodu).
Alternatywnie - po odbiorze wiadomości z "Przerwij" w metodzie breakpoint będziemy wołać jakieś exit() albo coś w tym stylu.

Do zrobienia:
- dodanie pliku .proto i wygenerowanie kodu C++/Java z wiadomościami sterującymi
- dodanie do structs.proto dodatkowej zbiorczej struktury, która zawierałaby wszystkie możliwe sety - w przypadku transferu danych będziemy wszystko przesyłać tym jednym rodzajem wiadomości.
- implementacja schematu komunikacji zgodnie z #6
- dodatkowo, z tego co zauważyłem, na końcu metody flushBuffer() czyszczony jest tyko jeden set - powinny być wszystkie

**Comment by ew940709** [comment]
Wszystko dodane w JavaAPI
